// Canonical definition of the 4 subscription plans. Used both by the manual
// seed script (scripts/seedPlans.js) and by the startup auto-seed
// (utils/seedPlans.js) so the two never drift apart.
const DEFAULT_PLANS = [
  {
    name: 'Free',
    price: 0,
    durationDays: 365, // valid for 1 year
    sortOrder: 1,
    features: {
      aiDocuments: 20,
      manualDocuments: 20,
      desktopAccess: true,
      mobileAppAccess: true,
      excelDownload: false,
      clientLimit: 20,
      appNotificationRenewal: true,
      whatsappRenewal: false,
      customizedPolicyDownload: false,
      personalisedQuotation: false,
      processingSpeed: 'Standard',
      support: 'Standard',
    },
  },
  {
    name: 'Go',
    price: 99,
    durationDays: 90,
    sortOrder: 2,
    features: {
      aiDocuments: 50,
      manualDocuments: 50,
      desktopAccess: true,
      mobileAppAccess: true,
      excelDownload: true,
      clientLimit: 50,
      appNotificationRenewal: true,
      whatsappRenewal: false,
      customizedPolicyDownload: false,
      personalisedQuotation: false,
      processingSpeed: 'Fast',
      support: 'Standard',
    },
  },
  {
    name: 'Plus',
    price: 199,
    durationDays: 90,
    sortOrder: 3,
    features: {
      aiDocuments: 200,
      manualDocuments: 200,
      desktopAccess: true,
      mobileAppAccess: true,
      excelDownload: true,
      clientLimit: 200,
      appNotificationRenewal: true,
      whatsappRenewal: true,
      customizedPolicyDownload: true,
      personalisedQuotation: true,
      processingSpeed: 'Accelerated',
      support: 'Priority',
    },
  },
  {
    name: 'Pro',
    price: 499,
    durationDays: 90,
    sortOrder: 4,
    features: {
      aiDocuments: 500,
      manualDocuments: 500,
      desktopAccess: true,
      mobileAppAccess: true,
      excelDownload: true,
      clientLimit: 0,
      appNotificationRenewal: true,
      whatsappRenewal: true,
      customizedPolicyDownload: true,
      personalisedQuotation: true,
      processingSpeed: 'Highest',
      support: 'Priority',
    },
  },
]

module.exports = { DEFAULT_PLANS }
